steps:
- name: python:3.7
  args: ['bash', '-c', 'pip install --upgrade pip && pip install invoke==1.4.1 PyYAML==5.3.1 google-cloud-storage==2.3.0 google-cloud-secret-manager==2.11.0 && invoke download-all-credentials' ]
  id: Download pipeline credentials

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/tmg-data-preprod/clarity-master-pipeline-v2:$COMMIT_SHA', '.']
  id: Make the docker image

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/tmg-data-preprod/clarity-master-pipeline-v2:$COMMIT_SHA']
  id: Push the docker image

- name: python:3.7
  args: ['bash', '-c', 'pip install --upgrade pip && pip install invoke==1.4.1 PyYAML==5.3.1 google-cloud-storage==2.3.0 google-cloud-secret-manager==2.11.0 && invoke deploy-airflow dev $COMMIT_SHA' ]
  id: Deploy to Airflow