steps:
- name: python:3.7
  args: ['bash', '-c', 'pip install --upgrade pip && pip install invoke==1.4.1 PyYAML==5.3.1 google-cloud-storage==1.27.0 && invoke deploy-airflow dev batch && invoke deploy-airflow dev microbatch' ]
  id: Deploy to Airflow
