apiVersion: apps/v1
kind: Deployment
metadata:
  name: sid-production-sql-proxy-deployment
  labels:
    app: sid-production-sql-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sid-production-sql-proxy
  template:
    metadata:
      labels:
        app: sid-production-sql-proxy
    spec:
      containers:
      - name: sid-production-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.10
        command: ["/cloud_sql_proxy",
                  "-instances=tmg-reporting:europe-west1:sid-production=tcp:0.0.0.0:3306",
                  "-credential_file=/secrets/cloudsql/sid-production-tmg-datalake.json"]
        volumeMounts:
        - name: sid-production-cloudsql-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      affinity: 
          nodeAffinity: 
              requiredDuringSchedulingIgnoredDuringExecution: 
                  nodeSelectorTerms:
                      - matchExpressions: 
                          - key: 'cloud.google.com/gke-nodepool'
                            operator: 'In'
                            values: 
                              - 'node-for-images'
      volumes:
      - name: sid-production-cloudsql-credentials
        secret:
          secretName: sid-production-cloudsql-credentials
---
kind: Service
apiVersion: v1
metadata:
  name: sid-production-sql-proxy-service
spec:
  selector:
    app: sid-production-sql-proxy
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
