default_args:
  catchup: false
  delay: 2
  retries: 3
  schedule_interval: 30 7 * * *
  starting_date: '20240314'

pipelines:
  dim_spark_campaigns:
    args:
      - execution_date: "{{ ds_nodash }}"
      - next_execution_datetime: "{{ next_execution_date }}"
    image: eu.gcr.io/tmg-data-prod/clarity-dim-spark-campaigns-pipeline
    tag: 1.0.2

  dim_spark_campaigns_urls:
    args:
      - execution_date: "{{ ds_nodash }}"
      - next_execution_datetime: "{{ next_execution_date }}"
    image: eu.gcr.io/tmg-data-prod/clarity-dim-spark-campaigns-urls-pipeline
    tag: 2.1.3

  dfp:
    args:
      - execution_date: "{{ ds_nodash }}"
      - next_execution_datetime: "{{ next_execution_date }}"
    image: eu.gcr.io/tmg-data-prod/clarity-dfp-pipeline
    tag: 1.6.0

  competition_formstack:
    args:
      - execution_date: "{{ ds_nodash }}"
      - next_execution_datetime: "{{ next_execution_date }}"
    image: eu.gcr.io/tmg-data-prod/clarity-formstack-pipeline
    tag: 1.0.2

  video_youtube:
    args:
      - execution_date: "{{ ds_nodash }}"
      - next_execution_datetime: "{{ next_execution_date }}"
    image: eu.gcr.io/tmg-data-prod/clarity-youtube-pipeline
    tag: 1.0.1

  tcuk:
    args:
      - execution_date: "{{ ds_nodash }}"
      - next_execution_datetime: "{{ next_execution_date }}"
    image: eu.gcr.io/tmg-data-prod/clarity-tcuk-pipeline
    tag: 1.5.1

  article_tcuk:
    args:
      - execution_date: "{{ ds_nodash }}"
      - next_execution_datetime: "{{ next_execution_date }}"
    image: eu.gcr.io/tmg-data-prod/clarity-article-tcuk-pipeline
    tag: 1.0.0

  applenews:
    args:
      - execution_date: "{{ ds_nodash }}"
      - next_execution_datetime: "{{ next_execution_date }}"
    image: eu.gcr.io/tmg-data-prod/clarity-applenews-pipeline
    tag: 1.0.4

  article_applenews:
    args:
      - execution_date: "{{ ds_nodash }}"
      - next_execution_datetime: "{{ next_execution_date }}"
    image: eu.gcr.io/tmg-data-prod/clarity-article-applenews-pipeline
    tag: 1.0.1

  liveapp:
    args:
      - execution_date: "{{ ds_nodash }}"
      - next_execution_datetime: "{{ next_execution_date }}"
    image: eu.gcr.io/tmg-data-prod/clarity-appdata-pipeline
    tag: 1.2.7

  editionapp:
    args:
      - execution_date: "{{ ds_nodash }}"
      - next_execution_datetime: "{{ next_execution_date }}"
    image: eu.gcr.io/tmg-data-prod/clarity-edition-app-pipeline-dbt
    tag: 2.1