dbt:
  repositories:
    dim-spark-campaign: git@github.com:telegraph/clarity-dim-spark-campaigns-pipeline
  profile: 'gs://clarity-configs/clarity-dbt-profiles.yml'
  image: 'eu.gcr.io/tmg-datalake/sid-dbt-runtime:1.0.0'
  environment: dev



pipelines:
  dim-spark-campaigns:
    type: DBT 
    git_repository: dim-spark-campaign
    git_branch: DT-4316
    dbt_vars:
      materialized: table
    dbt_tag: 
    
