####################################
          #   STEP 1    #
######## dbtRunner config ##########
####################################

dbt:
  repositories:
    dim-spark-campaign: git@github.com:telegraph/clarity-dim-spark-campaigns-pipeline
  profile: 'gs://clarity-configs/clarity-dbt-profiles.yml'
  image: 'eu.gcr.io/tmg-datalake/sid-dbt-runtime:1.0.0'
  environment: dev



pipelines:
  dim-spark-campaigns:
    type: DBT 
    git_repository: dim-spark-campaign
    git_branch: DT-4316
    dbt_vars:
      materialized: table
    dbt_tag: 
    




###########################################
      #     STEP 2      #
##### ClarityPublishJob config part 1 #####
###########################################


logger:
  push_to_pubsub: false

project: tmg-plat-dev

pubsub:
  subscription_name: #sid-consumer

mysql:
  instance_name: tmg-plat-dev:europe-west1:clarity-test
  database: clarity
  tmp_mysql_schema: 
  host: sqlproxy-service-clarity-dev #'192.158.29.106' #sqlproxy-service-clarity-dev
  user: root
  password: root


bq:
  dataset: clairty_publishdata_test
  sanity_check_dataset: clairty_publishdata_test
  sanity_check_table: publishJob_status
  delta_dataset: sid_transfer_deltas

gcs:
  bucket: clarity-configs
  file_ending: .csv


transfers:

  dim-spark-campaigns:
    transfer:
      method: truncate
      load_data_infile: load_dim_spark_campaigns.sql

    bq_table: dim_spark_campaigns
    mysql_table: dim_spark_campaigns
    table_indexes:
      - name: campaign_index
        columns: campaign




###########################################
      #     STEP 3     #
##### ClarityPublishJob config part 2 #####
###########################################

publisher:
  image: claritypublisherjob
  version: 1.0.6
  configuration_file: gs://clarity-configs/clarity_master_pipeline_v2.yml
  google_app_credentials: '/google-keys/dev-pipeline.json'


  pipelines:
    dim-spark-campaigns:
      - transfer_name: dim-spark-campaigns








