####################################
          #   STEP 1    #
######## dbtRunner config ##########
####################################

dbt:
  repositories:
    dim-spark-campaign: git@github.com:telegraph/clarity-dim-spark-campaigns-pipeline
    dfp: git@github.com:telegraph/clarity-dfp-pipeline.git
  profile: 'gs://clarity-configs/clarity-dbt-profiles.yml'
  image: 'eu.gcr.io/tmg-datalake/sid-dbt-runtime:1.0.0'
  environment: dev



pipelines:

  dim-spark-campaigns:
    type: DBT 
    git_repository: dim-spark-campaign
    git_branch: DT-4316
    dbt_vars: 
      materialized: table
    dbt_tag: 
    af_downstreams:
      - dfp
  
  dfp:
    type: DBT
    git_repository: dfp
    git_branch: DT-4323
    dbt_vars: 
      materialized: table
    dbt_tag:




###########################################
      #     STEP 2      #
##### ClarityPublishJob config part 1 #####
###########################################


logger:
  push_to_pubsub: false

project: tmg-plat-dev

pubsub:
  subscription_name: #sid-consumer

mysql:
  instance_name: tmg-plat-dev:europe-west1:clarity-test
  database: clarity
  tmp_mysql_schema: 
  host: '192.158.29.106' #'192.158.29.106' #sqlproxy-service-clarity-dev
  user: root
  password: root


bq:
  dataset: clairty_publishdata_test
  sanity_check_dataset: clairty_publishdata_test
  sanity_check_table: publishJob_status
  delta_dataset: sid_transfer_deltas

gcs:
  bucket: clarity-configs
  file_ending: .csv


transfers:

  dim-spark-campaigns:
    transfer:
      method: truncate
      load_data_infile: load_dim_spark_campaigns.sql
    bq_table: dim_spark_campaigns
    mysql_table: dim_spark_campaigns
    table_indexes:
      - name: campaign_index
        columns: campaign

  addelivery-hub-dfp:
    transfer:
      method: truncate
      load_data_infile: load_addelivery_hub_dfp.sql
    bq_table: addelivery_hub_dfp
    mysql_table: addelivery_hub_dfp
    table_indexes: 
      - name: campaign_index
        columns: campaign

  addelivery-ros-dfp:
    transfer:
      method: truncate
      load_data_infile: load_addelivery_ros_dfp.sql
    bq_table: addelivery_ros_dfp
    mysql_table: addelivery_ros_dfp
    table_indexes: 
      - name: campaign_index
        columns: campaign

  addelivery-ros-allplatforms:
    transfer:
      method: truncate
      load_data_infile: load_addelivery_ros_allplatforms.sql
    bq_table: addelivery_ros_allplatforms
    mysql_table: addelivery_ros_allplatforms
    table_indexes: 
      - name: campaign_index
        columns: campaign

  addelivery-hub-allplatforms:
    transfer:
      method: truncate
      load_data_infile: load_addelivery_hub_allplatforms.sql
    bq_table: addelivery_hub_allplatforms
    mysql_table: addelivery_hub_allplatforms
    table_indexes: 
      - name: campaign_index
        columns: campaign


###########################################
      #     STEP 3     #
##### ClarityPublishJob config part 2 #####
###########################################

publisher:
  image: claritypublisherjob
  version: 1.0.7
  configuration_file: gs://clarity-configs/clarity_master_pipeline_v2.yml
  google_app_credentials: '/google-keys/dev-pipeline.json'


  pipelines:
    dim-spark-campaigns:
      - transfer_name: dim-spark-campaigns

    dfp:
      - transfer_name: addelivery-ros-dfp
        af_downstreams: addelivery-ros-allplatforms
      - transfer_name: addelivery-hub-dfp
        af_downstreams: addelivery-hub-allplatforms






